name: ci
on:
dev
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

  pull_request:
    branches: [ dev, main ]
  push:
    branches: [ dev, main ]
main
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CI is alive ✅"
